"""Add image_url column to images table

Revision ID: 42275206c18b
Revises: d2b6b610a378
Create Date: 2026-03-06 00:34:29.192769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "42275206c18b"
down_revision: Union[str, Sequence[str], None] = "d2b6b610a378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("image_url", sa.String(length=500), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "image_url")
    # ### end Alembic commands ###
